const SET_PRODUCTS = 'SET_PRODUCTS';
const SET_IS_LOADING_PRODUCTS = 'SET_IS_LOADING_PRODUCTS';
const SET_ERROR_PRODUCTS = 'SET_ERROR_PRODUCTS';
const CLEAR_ERROR_PRODUCTS = 'CLEAR_ERROR_PRODUCTS';
const CLEAR_ALL_PRODUCTS = 'CLEAR_ALL_PRODUCTS';

export {
  SET_PRODUCTS,
  SET_IS_LOADING_PRODUCTS,
  SET_ERROR_PRODUCTS,
  CLEAR_ERROR_PRODUCTS,
  CLEAR_ALL_PRODUCTS,
};
